[package]
name = "reload-demo"
version = "0.1.0"
authors = ["Caleb Jones <code@calebjones.net>"]

[lib]
name = "reloadapp"
crate-type = ["cdylib"]

[dependencies]
live-reload = { version="0.2", path="../live-reload" }
