[package]
name = "reload-demo"
version = "0.2.0"
authors = ["Caleb Jones <code@calebjones.net>"]

[lib]
name = "reloadable"
crate-type = ["cdylib"]

[dependencies]
live-reload = { version="0.2", path=".." }
